### ISSUE TITLE
[BUG] Log explorer query crashed when type :something:

### ISSUE THREAD

**Issue by c3s4rfred** [utmstack/UTMStack#217]
**Describe the bug**
If you type something like :something: the endpoint call returns 500 Internal error under some conditions, maybe related with the amount of data in the cluster.

**To Reproduce**
1. Go to 'Log explorer' menu
2. Type ':something:' in query search box
3. See error

**Screenshots**
![image](https://github.com/utmstack/UTMStack/assets/17603499/cd81d1b1-b594-429a-8575-1a26e5eb74e5)
![image](https://github.com/utmstack/UTMStack/assets/17603499/0133890d-34df-4eed-a695-30efa14df621)
New image 12-01-2023
![image](https://github.com/utmstack/UTMStack/assets/17603499/1a3758c3-140b-4eea-b782-1b5d248a199b)
![image](https://github.com/utmstack/UTMStack/assets/17603499/9f39f52e-d659-4260-9f4a-bb509f9f013f)

**Environment**
 - UTMStack 10.2.0 QA

**Possible solution**
May be, adding scape character for some special chars as : ; . \ | <>

**Comment by c3s4rfred** [comment]
The change that close this issue was deployed but still happening see that images attached

**Comment by leonardomoralopez89** [comment]
The reserved characters for the OpenSearch query string query were escaped, but we received an error message indicating that all shards have failed. This differs from the usual message when the query string fails due to an unescaped reserved character. This may be a resource issue within the QA environment, as this is a costly search.
