### ISSUE TITLE
[BUG] I can't login after installing from the ISO

### ISSUE THREAD

**Issue by gjannece** [utmstack/UTMStack#404]
So I might have missed something super basic, but I used the "utmstack-v10-1-0-autoinstall.iso" in Vmware Fusion (intel based mac) and I went through the installer and watched the console logs until it completed. After it completed, I rebooted it and wait a bit for the prompt to come up. I load up a browser and point it to my new install of UTM and it shows me the login screen. Great!
How do I login? I looked at the documents and there doesn't seem to be anything for the ISO install, just the master / manual install. I do see in the install logs that there was a root password generated in /root/ but I can't get to it because I can't login. 

Am I missing something? 

1. Download "utmstack-v10-1-0-autoinstall.iso"
2. Go through UTM installer
3. Reboot when asked
4. Open browser to your new installed UTM server
5. Get stuck because you can't login as admin or root. In either the browser or the console on the VM

Sorry if I missed something basic, but maybe seeing the password before reboot or something would be useful.

**Comment by jdieguez89** [comment]
Hi @gjannece, when you install using the ISO you can find the password and other generated configurations in /root/UTMStack.yml, please check the [UTMStack Documentation Installation page](https://docs.utmstack.com/Installation/MasterServerInstallation) for more details

**Comment by jdieguez89** [comment]
@gjannece please let us know if the issue persist, i will close the issue

**Comment by gjannece** [comment]
I'm re-opening this because it looks like you didn't even read my bug report. I am trying not to be rude, but I need you to re-read the bug report. You seem to be talking about installing UTM on a Ubuntu that I already have root access to. When I install UTM using the UTM iso mentioned above. 
When you use the UTM ISO installer, it only asks how to lay out the harddrive partitions and begins the installation. I don't get asked to setup a user or am given the root password in the console logs. I only seem a mention that the root password is generated and can be found in /root/UTMStack.yml. I'm going to remind you that I had already posted that I couldn't login to the system to get the root password.

**Comment by gjannece** [comment]
The link to the auto installer is here. https://utmstack.com/install/

**Comment by osmontero** [comment]
Hello @gjannece,

Thank you for contacting us about your issue with installing UTMStack. We apologize for any inconvenience this may have caused you.

We have reviewed the email thread and noticed that you had trouble finding the default username and password for the operating system when you used the ISO file. Here is the information you need:

User: utmstack
Password: utmstack

We are sorry that this information was not clearly stated in the official documentation. We are currently working on some important features for UTMStack and we have not been able to update the documentation as frequently as we would like.

However, since UTMStack is an open source project, free, and under the AGPL v3 license, we welcome and appreciate the contribution of the community to keep the documentation updated. If you have any suggestions or corrections for the documentation, you can make a pull request to the repository: [Documentation](https://github.com/utmstack/Documentation)

We also kindly ask you to respect the community code of conduct and refrain from using aggressive or disrespectful language when communicating with us or other users. We are all volunteers who offer our time and skills to create a free, open source product and to help each other. We expect a professional and courteous attitude from everyone who participates in this project.

Thank you for your understanding and cooperation. We hope you enjoy using UTMStack and we look forward to hearing from you again.

**Comment by karlbrown87** [comment]
> Hi @jdieguez89,
> 
> I'm re-opening this because it looks like you aren't fully understanding my bug report didn't even read my bug report. Your solution was mentioning to read the instructions, but the instructions are for installing UTM on an OS you already have root access to. I am not doing this. I am installing UTM with the dedicated UTM auto install iso which is found on the main website.
> 
> When you use the UTM ISO installer, it only asks how to lay out the harddrive partitions and begins the installation. I don't get asked to setup a user or am given the root password in the console logs. I only seem a mention that the root password is generated and can be found in /root/UTMStack.yml. I am guessing this is huge oops on UTMs side and I wanted to explain the huge bug and am hoping to either get a new version or a solution that doesn't involve mounting the root partition on another linux system to zero out the root password.
> 
> If I am missing something or have completely missed how else to gain access to the auto installed OS, please let me know, but the link you provided begins with the assumption that I already have root access to the OS.
> 
> Thanks!

Hi gjannece, the default username and password for bash console in the ISO installation is utmstack : utmstack

**Comment by osmontero** [comment]
A note with the default OS credentials was added to the README.md and the official documentation.
