### ISSUE TITLE
[FEATURE] Allow sending raw syslogs

### ISSUE THREAD

**Issue by volitank** [utmstack/UTMStack#485]
I'm currently evaluating UTMStack for our company. I have ran into some issues that seems like it may be a blocker for us.

From the integrations is seems like the way to get syslogs is to install the linux agent. In the case for our Ubiquity switches this isn't an option. They can only send syslogs UDP to IP:PORT. Enabling This would allow UTM to be much more versatile in how they can receive logs. It may be possible that there is a better way, but I'm unable to find a solution through the UI/Docs.

Additionally in my self hosted instance I've set up it seems like a lot of integrations are not available that are shown on the website. For example the pfsense and suricata integrations.

Below is an image where I was able to hack together a solution somewhat, as logstash does have this functionality, I just created my own pipeline in `/utmstack/logstash/pipelines/syslog_raw`. The issue with doing this is that it's not easy to open a port for syslogs like this in the docker containers, and I'm unsure if doing so would break something anyway.

It would be nice to have a solution for ingesting raw syslogs. right now we only have it ingesting O365 logs which is working wonderfully.

![image](https://github.com/utmstack/UTMStack/assets/23148438/f49f1b79-ee66-4d72-af26-287bc0b25300)

**Comment by volitank** [comment]
Unrelated but I also don't see anything in the docs about updating UTMStack when there are new releases. Am I supposed to just run the installer again?

**Comment by osmontero** [comment]
> Unrelated but I also don't see anything in the docs about updating UTMStack when there are new releases. Am I supposed to just run the installer again?

Please send your questions by using the [Discussions](https://github.com/utmstack/UTMStack/discussions) option.

**Comment by osmontero** [comment]
Hello,

You can install the Linux agent in a small Linux or Windows VM or container and configure the agent to receive logs from your Syslog device. Then, configure your device to send logs to that VM.

There is a generic Syslog integration for that case (with a guide on how to configure it).

After that, you can add your own filter to the pipeline through the UTMStacks UI to ensure your logs are being parsed correctly.

We do not receive logs from Syslog directly to UTMStack Server because they cannot be authenticated, and the most common scenarios involve having UTMStack hosted on a different network than the devices being monitored. Therefore, we made agents capable of acting as proxies for those use cases.
