### ISSUE TITLE
[BUG] Incorrect IPs for Datasources

### ISSUE THREAD

**Issue by global-H** [utmstack/UTMStack#503]
Datasources when installed for the first time (for example, using Windows integartion via powershell), are assigned a strange IP which seems to be more about the OVH SAS server in Canada, than the actual IP of the datasource. 

It is expected that the IP of the datasource is shown and used there.   In logs, the datasources similarly list with the incorrect Source IP in v10.  

The following IPs are all incorrect for the datasources:
![image](https://github.com/utmstack/UTMStack/assets/39112412/8cf97e22-27cd-4eee-8021-72be1ceedbdc)

Similarly, in logs, the same incorrect SourceIPs are showing.   Further, it is not possible to Add Column for the host.ip series: 
![image](https://github.com/utmstack/UTMStack/assets/39112412/f395afa4-1c83-44e9-a01c-32e037977387)
 
This issue is prevalent on both Windows and Linux datasource integrations. 

Unfortunately, none of the log's host.ip fields seem to show the correct IP address of the datasource.  

I did check for similar open issues, but didn't see any.  Please merge to any existing ticket if this is a known issue, thanks!

**Comment by c3s4rfred** [comment]
Hi, @global-H, when you install an agent, it takes the machine's IP according to your network configuration, please check, maybe you have or had a VPN or something like that at the installation moment. Please, tell us more about your installation, if you're in SaaS or on-premise installation, if on VM (characteristics). Note that UTMStack shouldn't be installed on a docker container, it already uses docker and may have network issues. About the fields, try with "host.ip", the field should be visible now, you can't access host.ip.1 because it is a value, not a field. 
Best regards

**Comment by global-H** [comment]
I'll have a closer look.  I thought i'd seen this host IP issue across several servers on the FS, whereby OVH SAS Canada is listed when indeed the datasources are known to be in UK, USA, etc.    Will highlight one next time I come across it, thanks
