### ISSUE TITLE
[FEATURE] Make MAC support official

### ISSUE THREAD

**Issue by rvald26** [utmstack/UTMStack#527]
**Is your feature request related to a problem? Please describe.**
UTMStack has been supporting MAC for a while now using the homebrew install of syslog,

**Describe the solution you'd like**
 Make it official inside the integrations list and deploy a filter that will handle parsing.

**Comment by osmontero** [comment]
UTMStack supports macOS as an official integration by using Syslog since version 8, with an integration guide and filter. However, establishing syslog connections directly to the UTMStack server is not supported. Instead, you must configure it to send logs to an agent that acts as a proxy between UTMStack and your syslog device, sending logs through the internet in an encrypted manner and securing the authentication.
