### ISSUE TITLE
poor choice of disk use not following OS security guidlines

### ISSUE THREAD

**Issue by apb1966** [utmstack/UTMStack#843]
The installer process requires 30GB of disk in /

this should be a user defined FS to be used and not /

using / as a data store for applications is a poor security choice, check NIST standards for OS builds you will find segmented OS mount points security ( been like this for years) )

allow data location to be configured for installer to check

**Comment by osmontero** [comment]
Hi apb1966.

UTMStack stores user data in /utmstack if you want to attach an additional disk to it for compliance of your choice, that is the correct route. However, UTMStack requires 30GB of disk space in / due to the installation of the Docker engine and other dependencies including Docker images and temporary disks for containers.

We are not open to including unnecessary configurations that increase the complexity of the platform or the learning curve.

For future requests, be sure to first go through the documentation and discussion forum on GitHub, and if you still need to open an issue, use the templates we have provided for that.
